# -*- coding: utf-8 -*-
"""Prediksi Kelulusan  Mahasiswa

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SNNagRdHyw1_Y9D3_-wkd_1N6VgldoMj
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

url = 'https://raw.githubusercontent.com/RafiFadhal/Prediksi-Kelulusan-Mahasiswa/main/student-por.csv'
df = pd.read_csv(url, sep=';')

df['lulus'] = df['G3'].apply(lambda x: 1 if x >= 10 else 0)

X = df.drop(['G3', 'lulus'], axis=1)
X = pd.get_dummies(X, drop_first=True)
y = df['lulus']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = GaussianNB()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Akurasi:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))